# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: ride_share
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 12345678


development:
  <<: *default


test:
  <<: *default
  database: caixa_test
